#!/usr/bin/env python3
"""Persistence gate: declared format shapes change only with a record.

Every format the plane writes to disk is adopter user data. This gate
enforces the acknowledgment chain documented in docs/persistence/README
(D63): a shape descriptor under ``docs/persistence/schemas/`` may only
move together with a record under ``docs/persistence/changes/`` that
chains to its predecessor and classifies the compatibility impact.

Judged here, fail loud (rule 5):

- schema descriptors parse, use known ``kind`` values, and name their
  artifact/writer/fields;
- records contain exactly one fenced JSON block with ``record``,
  ``date``, ``class`` (baseline/compatible/breaking) and a ``changes``
  object; the filename's number matches; unfinished drafts containing
  ``TODO`` are red;
- per type the chain is linear: the first touching record is the
  ``baseline`` (before null), every successor's ``before`` equals the
  predecessor's ``after``, and the newest ``after`` equals the sha256
  of the LIVE schema file — the anchor that makes an unacknowledged
  schema edit red;
- ``catalog.json`` (generated by ``--update``) is fresh.

What this honestly does NOT prove: that the code conforms to the
declared shapes — that is review and tests. Exit codes follow D2:
0 intact, 1 violations, 2 config/usage error.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT_DIR = Path("docs/persistence")
SCHEMA_KINDS = {"json-object", "jsonl-lines", "yaml-object",
                "markdown-contract"}
RECORD_CLASSES = {"baseline", "compatible", "breaking"}
FENCE_RX = re.compile(r"```json\s*\n(.*?)```", re.DOTALL)
LEADING_NUM = re.compile(r"^(\d{4})-")
CLAUDE_MARK = "TODO"


def _die(msg: str) -> None:
    print(f"persistence: {msg}", file=sys.stderr)
    raise SystemExit(2)


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_schemas(root: Path) -> dict[str, tuple[Path, dict]]:
    schemas: dict[str, tuple[Path, dict]] = {}
    for path in sorted((root / ROOT_DIR / "schemas").glob("*.schema.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            _die(f"{path.relative_to(root)}: unreadable schema ({e})")
        if not isinstance(data, dict):
            _die(f"{path.relative_to(root)}: schema is not an object")
        missing = [k for k in ("type", "artifact", "kind", "writer",
                               "readers", "fields") if k not in data]
        if missing:
            _die(f"{path.relative_to(root)}: missing key(s) "
                 f"{', '.join(missing)}")
        if data["kind"] not in SCHEMA_KINDS:
            _die(f"{path.relative_to(root)}: unknown kind "
                 f"'{data['kind']}' (known: {', '.join(sorted(SCHEMA_KINDS))})")
        schemas[data["type"]] = (path, data)
    if not schemas:
        _die(f"{ROOT_DIR / 'schemas'}: no schema descriptors — the "
             f"inventory cannot be empty")
    return schemas


def load_records(root: Path) -> list[tuple[str, dict, str]]:
    records = []
    changes = root / ROOT_DIR / "changes"
    for path in sorted(changes.glob("*.md")):
        if path.name.endswith(".zh.md"):
            continue  # the en side is the machine-readable record
        text = path.read_text(encoding="utf-8")
        num = LEADING_NUM.match(path.name)
        if not num:
            _die(f"{path.relative_to(root)}: filename must start with "
                 f"NNNN-")
        blocks = FENCE_RX.findall(text)
        if len(blocks) != 1:
            _die(f"{path.relative_to(root)}: expected exactly one fenced "
                 f"json block, found {len(blocks)}")
        try:
            rec = json.loads(blocks[0])
        except json.JSONDecodeError as e:
            _die(f"{path.relative_to(root)}: record json unreadable ({e})")
        for key in ("record", "date", "class", "changes"):
            if key not in rec:
                _die(f"{path.relative_to(root)}: record missing '{key}'")
        if rec["record"] != num.group(1):
            _die(f"{path.relative_to(root)}: record number "
                 f"{rec['record']!r} does not match the filename")
        if rec["class"] not in RECORD_CLASSES:
            _die(f"{path.relative_to(root)}: unknown class "
                 f"{rec['class']!r}")
        if not isinstance(rec["changes"], dict) or not rec["changes"]:
            _die(f"{path.relative_to(root)}: 'changes' must be a "
                 f"non-empty object of type -> {{before, after}}")
        if CLAUDE_MARK in text:
            print(f"persistence: {path.relative_to(root)}: unfinished "
                  f"draft (contains TODO)", file=sys.stderr)
            raise SystemExit(1)
        records.append((num.group(1), rec, path.name))
    if not records:
        _die(f"{ROOT_DIR / 'changes'}: no records — a declared inventory "
             f"needs its baseline")
    return records


def verify_chain(root: Path, schemas: dict, records) -> list[str]:
    problems: list[str] = []
    live = {t: _digest(p) for t, (p, _) in schemas.items()}
    latest: dict[str, tuple[str, str]] = {}
    for num, rec, name in records:  # sorted by filename == record order
        for typ, ch in sorted(rec["changes"].items()):
            if typ not in schemas:
                problems.append(f"{name}: type '{typ}' has no schema "
                                f"descriptor")
                continue
            if not isinstance(ch, dict) or set(ch) != {"before", "after"}:
                problems.append(f"{name}: '{typ}' must be exactly "
                                f"{{before, after}}")
                continue
            prev = latest.get(typ)
            if rec["class"] == "baseline" or prev is None:
                if ch["before"] is not None:
                    problems.append(
                        f"{name}: '{typ}' first record must seed with "
                        f"before: null")
            else:
                if ch["before"] != prev[1]:
                    problems.append(
                        f"{name}: '{typ}' before digest does not chain "
                        f"to {prev[0]}'s after")
            if not isinstance(ch["after"], str) or len(ch["after"]) != 64:
                problems.append(f"{name}: '{typ}' after is not a sha256")
            else:
                latest[typ] = (name, ch["after"])
    for typ, (name, after) in sorted(latest.items()):
        if after != live[typ]:
            problems.append(
                f"{typ}: live schema digest differs from {name}'s after — "
                f"touching a schema without a record (or a stale record) "
                f"is a violation; land the acknowledgment in the same PR")
    for typ in sorted(set(schemas) - set(latest)):
        problems.append(f"{typ}: schema declared but no record covers it")
    return problems


def build_catalog(root: Path, schemas: dict, records) -> dict:
    latest: dict[str, tuple[str, str]] = {}
    for num, rec, name in records:
        for typ, ch in rec["changes"].items():
            if isinstance(ch, dict) and isinstance(ch.get("after"), str):
                latest[typ] = (name, ch["after"])
    return {"types": {t: {"schema": f"docs/persistence/schemas/{t}.schema.json",
                          "digest": _digest(p),
                          "latest_record": latest[t][0]}
                       for t, (p, _) in sorted(schemas.items())
                       if t in latest}}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="check_persistence")
    parser.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    parser.add_argument("--update", action="store_true",
                        help="regenerate docs/persistence/catalog.json")
    args = parser.parse_args(argv)
    root = Path(args.root)
    schemas = load_schemas(root)
    records = load_records(root)

    problems = verify_chain(root, schemas, records)
    if args.update:
        catalog = build_catalog(root, schemas, records)
        path = root / ROOT_DIR / "catalog.json"
        path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2)
                        + "\n", encoding="utf-8")
        print(f"persistence: wrote {path.relative_to(root)} "
              f"({len(catalog['types'])} type(s))")
        return 1 if problems else 0
    catalog_path = root / ROOT_DIR / "catalog.json"
    if not catalog_path.exists():
        problems.append("docs/persistence/catalog.json missing — run "
                        "scripts/check_persistence.py --update")
    else:
        try:
            on_disk = json.loads(catalog_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            _die(f"{catalog_path.relative_to(root)}: unreadable catalog "
                 f"({e})")
        fresh = build_catalog(root, schemas, records)
        if on_disk != fresh:
            problems.append("docs/persistence/catalog.json is stale — "
                            "run scripts/check_persistence.py --update")

    if problems:
        for p in problems:
            print(f"persistence: {p}", file=sys.stderr)
        print(f"persistence: {len(problems)} violation(s)", file=sys.stderr)
        return 1
    print(f"persistence: {len(schemas)} declared type(s), "
          f"{len(records)} record(s) — chain intact, catalog fresh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
